---
repository_docker_key: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
repository_docker_release: stable
repository_docker: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ repository_docker_release }}"
